name: shoko_bases
description: "This package is a bases for MBS and Dialogs from the ShokoTeam, which aims to accelerate the development of both your and our projects"
version: 0.0.1
homepage: https://pub.dev/packages/shoko_ui
repository: https://github.com/ShoshiDeveloper/shoko_ui

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shoko_theme: ^0.0.1+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
